# Generated by Django 5.1.3 on 2024-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=True, max_length=255)),
                ('rut', models.CharField(default=True, max_length=255)),
                ('integrantes', models.CharField(default=True, max_length=255)),
            ],
        ),
    ]
